javavulnlab:
  build: .
  ports:
    - 8080:8080
  links:
    - mysql

mysql:
  image: mysql:5.7
  ports:
    - 3306:3306
  environment:
    - MYSQL_ROOT_PASSWORD=root

sonarqube:
    build: ./sonarqube
    ports:
      - 9000:9000
      - 9092:9092
