
services:
  jvl:
    image: cspf/jvl
    build: 
        dockerfile: ./Dockerfile
        context: ./
    ports:
      - 8080:8080
    links: 
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: abc
    command:
      - "--default-authentication-plugin=mysql_native_password"
