name: Java CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: |
        mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
        mvn test -B
    - name: Upload to CoPilot
      if: github.event_name == 'push' || github.event_name == 'pull_request' || github.event_name == 'workflow_dispatch'
      run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)