name: Example Workflow
#on:
#  push:
#    branches:
#      - main
#   schedule:
#     - cron:  '0 0 * * *'
#jobs:
 # security:
#    runs-on: windows-latest
#    steps:
#     - uses: actions/checkout@v2
#    - name: Create Black Duck Policy
#      env:
#        NODE_EXTRA_CA_CERTS: ${{ secrets.LOCAL_CA_CERT_PATH }}
#      uses: blackducksoftware/create-policy-action@v0.0.1
#      with:
#        blackduck-url: ${{ secrets.BLACKDUCK_URL }}
#        blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
#        policy-name: 'My Black Duck Policy For GitHub Actions'
#        no-fail-if-policy-exists: true
#    - name: Run Synopsys Detect
#      uses: synopsys-sig/detect-action@v0.3.0
#      env:
#        NODE_EXTRA_CA_CERTS: ${{ secrets.LOCAL_CA_CERT_PATH }}
      with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          detect-version: 8.9.0
          blackduck-url: ${{ secrets.BLACKDUCK_URL }}
          blackduck-api-token: ${{ secrets.BLACKDUCK_API_TOKEN }}
